import Footer from "./components/Footer";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// FIXED: Clean metadata without conflicts
export const metadata = {
  title: "CODELESS PAGES",
  description: "Generated by create next app",
  icons: {
    icon: "/image.png",
    shortcut: "/image.png",
    apple: "/image.png",
  },
};
const currentYear = new Date().getFullYear();
// FIXED: Remove manual head tags - let Next.js handle it
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-sans antialiased"
      >
        {children}
        <Toaster position="top-right" />
<Footer></Footer>
      </body>
    </html>
  );
}
