import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// FIXED: Clean metadata without conflicts
export const metadata = {
  title: "Amit Nath Work",
  description: "Generated by create next app",
  icons: {
    icon: "/image.png",
    shortcut: "/image.png",
    apple: "/image.png",
  },
};
const currentYear = new Date().getFullYear();
// FIXED: Remove manual head tags - let Next.js handle it
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer className=" text-white py-8 mt-auto border-t border-gray-700">
          <div className="container mx-auto px-6 max-w-6xl">
            <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
              <div className="text-center md:text-left">
                <p className="text-lg font-semibold mb-1">
                  Thank you for visiting!
                </p>
                <p className="text-gray-300 text-sm">
                  We appreciate your time and interest
                </p>
              </div>

              <div className="flex flex-col items-center md:items-end space-y-2">
                <div className="flex space-x-6 text-sm">
                  <a
                    href="#"
                    className="text-gray-300 hover:text-white transition-colors duration-200"
                  >
                    Privacy
                  </a>
                  <a
                    href="#"
                    className="text-gray-300 hover:text-white transition-colors duration-200"
                  >
                    Terms
                  </a>
                  <a
                    href="#"
                    className="text-gray-300 hover:text-white transition-colors duration-200"
                  >
                    Contact
                  </a>
                </div>
                <p className="text-gray-400 text-xs">
                  © {currentYear} All rights reserved
                </p>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-gray-700 text-center">
              <p className="text-xs text-gray-500">
                Made with ❤️ for an amazing experience
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}

// Alternative approach if the above doesn't work:
// Try this version with explicit metadata types
